# Generated automatically by openmrs SDK
version: '2'

services:
  db:
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: Admin123
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  web:
    build: web
    image: opengp:local
    depends_on:
      - db
    environment:
      DB_DATABASE: openmrs
      DB_HOST: db
      DB_USERNAME: openmrs
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: 'false'  # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'false'    # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
    volumes:
      - web-data:/usr/local/tomcat/.OpenMRS
      - /usr/local/tomcat/.OpenMRS/modules/ # used to mount persistent docker volume for modules
      - /usr/local/tomcat/.OpenMRS/owa/     # used to mount persistent docker volume for owa

volumes:
  db-data:
  web-data:
